services:
    # Form field types
    
    rk_eventphotos_module.form.type.field.multilist:
        class: RK\EventPhotosModule\Form\Type\Field\MultiListType
        arguments:
            - "@rk_eventphotos_module.listentries_helper"
        tags: ['form.type']
    
    rk_eventphotos_module.form.type.field.translation:
        class: RK\EventPhotosModule\Form\Type\Field\TranslationType
        tags: ['form.type']
    
    rk_eventphotos_module.form.type.field.upload:
        class: RK\EventPhotosModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_eventphotos_module.image_helper"
            - "@rk_eventphotos_module.upload_helper"
        tags: ['form.type']
