services:
    # Custom validators
    rk_eventphotos_module.validator.list_entry.validator:
        class: RK\EventPhotosModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@rk_eventphotos_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: rk_eventphotos_module.validator.list_entry.validator }
