files:
  - source: /Resources/translations/*.template.po
    ignore:
      - /Resources/translations/route.*
    translation: /Resources/translations/%file_name%.%two_letters_code%.po
    translation_replace:
      .template.: .
